### ISSUE TITLE
infura_mainnet_http = new ethers.providers.JsonRpcProvider(config.infura_mainnet_http, "homestead");

### ISSUE THREAD

**Issue by Starmandev** [0xScar/whale-watcher#2]
Gettings this error when trying to run. Do you have any idea how to fix it? I am running the recommended node version.

`infura_mainnet_http = new ethers.providers.JsonRpcProvider(config.infura_mainnet_http, "homestead");
                                                                        ^

TypeError: Cannot read property 'JsonRpcProvider' of undefined
    at Object.<anonymous> (C:\Users\petro\whale-watcher\main.js:8:44)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47`

**Comment by Starmandev** [comment]
downgraded the ethers to 5.7.2
